### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by rdewolff** [arunoda/meteor-up-legacy#391]
Getting this error while trying to `mup deploy` :

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------

Building Started: ../

Started TaskList: Deploy app 'emp-manager' (linux)
[178.62.191.96] - Uploading bundle
[178.62.191.96] ✔ Uploading bundle: SUCCESS
[178.62.191.96] - Setting up Environment Variables
[178.62.191.96] ✔ Setting up Environment Variables: SUCCESS
[178.62.191.96] - Invoking deployment process
[178.62.191.96] ✘ Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    Warning: Permanently added '178.62.191.96' (RSA) to the list of known hosts.
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------

    > fibers@1.0.5 install /opt/emp-manager/tmp/bundle/programs/server/node_modules/fibers
    > node ./build.js

    `linux-x64-v8-3.14` exists; testing
    Binary is fine; exiting
    underscore@1.5.2 node_modules/underscore

    eachline@2.3.3 node_modules/eachline
    └── type-of@2.0.1

    semver@4.1.0 node_modules/semver

    chalk@0.5.1 node_modules/chalk
    ├── ansi-styles@1.1.0
    ├── supports-color@0.2.0
    ├── escape-string-regexp@1.0.3
    ├── strip-ansi@0.3.0 (ansi-regex@0.2.1)
    └── has-ansi@0.1.0 (ansi-regex@0.2.1)

    fibers@1.0.5 node_modules/fibers

    source-map-support@0.2.8 node_modules/source-map-support
    └── source-map@0.1.32 (amdefine@0.1.0)
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    emp-manager stop/waiting
    emp-manager start/running, process 24618
    Waiting for 30 seconds while app is booting up
    Checking is app booted or not?
    emp-manager stop/waiting
    emp-manager start/running, process 24716
    ----------------------------------------------------------------------------
Completed TaskList: Deploy app 'emp-manager' (linux)
```

Any idea how to resolve this?

**Comment by arunoda** [comment]
Check your app logs.
do `mup logs -n 300`

**Comment by webstudiopro** [comment]
Same issue, my log says:

Log says:

root@zorro-HP-ProBook-4540s:/home/zorro/Dropbox/dev/apps/meteor/wiejoo-deployment# Failed to connect to localhost port 80: Connection timed out
Failed: command not found
root@zorro-HP-ProBook-4540s:/home/zorro/Dropbox/dev/apps/meteor/wiejoo-deployment# Latest deployment failed! Reverted back to the previous version.
No command 'Latest' found, did you mean:
Command 'aatest' from package 'libaa-bin' (universe)
Latest: command not found
root@zorro-HP-ProBook-4540s:/home/zorro/Dropbox/dev/apps/meteor/wiejoo-deployment# -----------------------------------STDOUT-----------------------------------
-----------------------------------STDOUT-----------------------------------: command not founds 

How can I fix this "command 'Latest' not found" error?

Thx
Benny

**Comment by edwardupton** [comment]
I'm getting a similar error with latest version, and also v0.97.  But in my case I can't even run 'mup logs' - there is no such folder as '/var/log/upstart' created on the server, even though the 'configuring upstart' process succeeded.

The only difference is the error thrown says 'curl: (7) Failed to connect to ::1: Network is unreachable'.

**Comment by edwardupton** [comment]
OK, i've switched to a new Google Cloud instance using Ubuntu (previously trying to run on Debian) and now I get the identical error as @rdewolff ... but still no log file to check

**Comment by arunoda** [comment]
@edwardupton Then try to do `mup logs -n 300`

**Comment by edwardupton** [comment]
@arunoda There doesn’t seem to be an upstart logs file:

[104.197.61.107] tail: [104.197.61.107] cannot open ‘/var/log/upstart/ld-news.log’ for reading[104.197.61.107] : No such file or directory[104.197.61.107]
On 27 Apr 2015, at 17:19, Arunoda Susiripala notifications@github.com wrote:

@edwardupton https://github.com/edwardupton Then try to do mup logs -n 300

**Comment by arunoda** [comment]
Hmm. Weird.

**Comment by arunoda** [comment]
Give me couple of weeks. I'm porting mup to use docker and all these issues will get fixed by that.
Currently, `mup setup` and `mup deploy` works. It's in the `mup2` branch.

**Comment by edwardupton** [comment]
So, the deployment finally worked on 'Ubuntu 14.04 x64 vmlinuz-3.13.0-43-generic' instance on DigitalOcean.  It seems there is some network security problem when deploying to Google Cloud Compute instance, using both 'ubuntu-1504-vivid-v20150422' and 'backports-debian-7-wheezy-v20150325' setups.

But there's no clue from the error handling exactly what the issue is.  Hopefully better error handling can follow after the docker port.  Good luck

**Comment by firdausramlan** [comment]
Ubuntu 15.04 default to systemd instead of upstart. That might cause the problem. Encounter this problem when upgrading from Ubuntu 14.10.

**Comment by arunoda** [comment]
Oh yes. I now noticed 1504. Yes, that was the one reason we are moving to docker. I don't need build init scripts for both systemd and upstart. Not a hard task but better if we can avoid it.

**Comment by rdewolff** [comment]
Logs are the following :

```
Connected
Ready
Connected
Ready
Ready
Stream error: Error: write after end
Stream error: Error: write after end
Stream error: Error: write after end
Stream error: Error: write after end
Closed
Timeout error: emp-web-47.zetcom.ch: Command timed out after 2 seconds
Closed
Timeout error: emp-web-47.zetcom.ch: Command timed out after 2 seconds
Closed
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #1
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #2
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #3
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #4
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #5
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #6
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #7
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #8
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #9
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #10
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #11
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #12
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #13
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #14
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #15
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #16
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #17
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #18
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #19
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #20
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #21
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #22
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #23
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #24
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
Kadira: completed instrumenting the app
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
```
Still not working. Any idea? Last time I did the deployment it worked.

**Comment by rdewolff** [comment]
Logs are the following :

```
Connected
Ready
Connected
Ready
Ready
Stream error: Error: write after end
Stream error: Error: write after end
Stream error: Error: write after end
Stream error: Error: write after end
Closed
Timeout error: emp-web-47.zetcom.ch: Command timed out after 2 seconds
Closed
Timeout error: emp-web-47.zetcom.ch: Command timed out after 2 seconds
Closed
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #1
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #2
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #3
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #4
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #5
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #6
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #7
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #8
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #9
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #10
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #11
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #12
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #13
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #14
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #15
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #16
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #17
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #18
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #19
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #20
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #21
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #22
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #23
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
error: Script restart attempt #24
Meteor requires Node v0.10.36 or later.
error: Forever detected script exited with code: 1
Kadira: completed instrumenting the app
 >> stepping down to gid: meteoruser
 >> stepping down to uid: meteoruser
Kadira: successfully authenticated
```

What's the proper way to fix the node version?

**Comment by rdewolff** [comment]
Am trying to update the node version in the `mup.json` to node v0.12.2 and see if this works.

**Comment by rdewolff** [comment]
Same error :(

**Comment by rdewolff** [comment]
Am trying a `mup setup` command now to update node.

**Comment by rdewolff** [comment]
Having previously updated the `nodeVersion` to 0.12.2 in the `mup.json` file and running `mup setup` did not work.

I had to ssh to the box and update manually update node via npm with the following commands :

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

After that, running :

`mup deploy`

Worked like a charm!

**Comment by thikari** [comment]
Hey,
i have also problem with mup deploy. Any idea what to fix here?

```
-----------------------------------STDERR-----------------------------------
t_dir=/root/.node-gyp/0.10.36',
gyp info spawn args   '-Dmodule_root_dir=/opt/hashtagteachers/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    ctory `/opt/hashtagteachers/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build'

```
> fibers@1.0.5 install /opt/hashtagteachers/tmp/bundle/programs/server/node_modules/fibers
> node ./build.js

`linux-x64-v8-3.14` exists; testing
Binary is fine; exiting
underscore@1.5.2 node_modules/underscore

semver@4.1.0 node_modules/semver

chalk@0.5.1 node_modules/chalk
├── ansi-styles@1.1.0
├── escape-string-regexp@1.0.3
├── supports-color@0.2.0
├── has-ansi@0.1.0 (ansi-regex@0.2.1)
└── strip-ansi@0.3.0 (ansi-regex@0.2.1)

eachline@2.3.3 node_modules/eachline
└── type-of@2.0.1

fibers@1.0.5 node_modules/fibers

source-map-support@0.2.8 node_modules/source-map-support
└── source-map@0.1.32 (amdefine@0.1.0)
Waiting for MongoDB to initialize. (5 minutes)
connected
hashtagteachers stop/waiting
hashtagteachers start/running, process 2750
Waiting for 250 seconds while app is booting up
Checking is app booted or not?
hashtagteachers stop/waiting
hashtagteachers start/running, process 3218
----------------------------------------------------------------------------
```
