### ISSUE TITLE
SSL setup keeps giving "Copying SSL certificate bundle: FAILED"

### ISSUE THREAD

**Issue by mbabauer** [arunoda/meteor-up-legacy#651]
I have the following setup w/ mupx:

``` json
{
  // Server authentication info
  "servers": [
    {
      "host": "dev.myserver.com",
      "username": "myuser",
      "pem": "../myuser_rsa",
      "env": {}
    }
  ],

  // Install MongoDB on the server. Does not destroy the local MongoDB on future setups
  "setupMongo": true,

  // Application name (no spaces).
  "appName": "myApp",

  // Location of app (local directory). This can reference '~' as the users home directory.
  // i.e., "app": "~/Meteor/my-app",
  // This is the same as the line below.
  "app": "../../",

  // Configure environment
  // ROOT_URL must be set to your correct domain (https or http)
  "env": {
    "PORT": 80,
    "UPSTART_UID": "myuser", // The user you want to run meteor as.
    "ROOT_URL": "http://dev.myserver.com"
  },

  "ssl": {
    "certificate": "./ssl-unified.crt", // this is a bundle of certificates
    "key": "./ssl.key", // this is the private key of the certificate
    //"pem": "./ssl.pem",
    "port": 443 // 443 is the default value and it's the standard HTTPS port
  },

  // Meteor Up checks if the app comes online just after the deployment.
  // Before mup checks that, it will wait for the number of seconds configured below.
  "deployCheckWaitTime": 15,

  // show a progress bar while uploading.
  // Make it false when you deploy using a CI box.
  "enableUploadProgressBar": false
}
```

If I run `mupx setup` I get the following:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”


Started TaskList: Setup (linux)
[dev.myserver.com] - Installing Docker
[dev.myserver.com] - Installing Docker: SUCCESS
[dev.myserver.com] - Setting up Environment
[dev.myserver.com] - Setting up Environment: SUCCESS
[dev.myserver.com] - Copying MongoDB configuration
[dev.myserver.com] - Copying MongoDB configuration: SUCCESS
[dev.myserver.com] - Installing MongoDB
[dev.myserver.com] - Installing MongoDB: SUCCESS
[dev.myserver.com] - Copying SSL certificate bundle
[dev.myserver.com] x Copying SSL certificate bundle: FAILED
    Failure
```

I have checked the certificate and the private key, and they both seem fine.  I also tried creating the .pem file, as suggested in the docs, but I get the following:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Invalid configuration file mup.json: SSL certificate file does not exists.
```

I also tried removing the `./` part of the cert file names, but got the same response.

All cert files are in the same folder as the mup.json, which is where I am running `mupx` from.  My folder structure looks something like:

```
myapp/
    ...other meteor stuff...
    mup/
        myuser_rsa
        dev/
            mup.json
            ssl.key
            ssl.crt
            ssl.pem
        prod/
            ...future Prod mupx setup...
```

To note, I stole the project folder structure and mupx setup from another project that seems to be working fine.

**Comment by MasterJames** [comment]
Thanks for the note about the template.  It seems unconventional and part of the problem (since it's unfamiliar).
I'm guessing the app path could be related.
I thought someone once said a true fully qualified path name helped so maybe try that to isolate that possibility.
It would seem it's looking for the pem there too possibly. Is that all the same in the template version? Double check it maybe.
Consider trying the example given in mupx Readme and do a test without your other example/template (which should work, to help isolate the difference/problem with your prefered unfamilar to me template'so way).
I'm guessing it's for babel post processed production files etc. Maybe there's a problem there.
It seemed like you just need your SSL stuff in the right folder. If you remove SSL settings it won't run that stud part of the script.
You can step manually through the code responsible to get a better understanding of the problem. 
Libs/TaskLists/Linux.sh

stud --test --config=/opt/stud/stud.conf

It tries to copy the pem to opt/stud the line above would test it if your SSHed  into the server.

**Comment by mbabauer** [comment]
Ok, so somehow when the setup ran, it copied the certificates out to `/opt/' + config.appName + '/config/bundle.crt` and `/opt/' + config.appName + '/config/private.key`, but instead of being files, they were directories.  Does that make any sense?  I nuked the /opt app folder, and it sprinted right past the SSL copy step.  I am not sure how it got bungled in such a way, but it's working now.

**Comment by codetheweb** [comment]
I had this exact same problem. Taking @mbabauer's advice, I trashed the `/opt/app` directory and it worked fine.  What's going on?

**Comment by fishdude** [comment]
I was struggling with this issue for a couple hours the other day. As soon as I changed my `appName` to one word, setup completed without issue.

changed:

```
"appName": "Random Name"
```

to:

```
"appName": "RandomName"
```

**Comment by twavis** [comment]
Just experienced same issue.  ‘bundle.crt was a directory.

I deleted the config directory and ran mupx setup, and the ssl copied over without a problem. I had the server setup originally without ssl, so perhaps the issue occurs when adding ssl to already setup server? Not sure but glad I found this information.

**Comment by j6k4m8** [comment]
Looks like `rm -rf /opt` is the (terrifying) way to go on this one.

**Comment by gdw2** [comment]
I'm seeing this too (key/cert showing up as directory instead of file).  Likely a problem with nodemiral? @arunoda

**Comment by markshust** [comment]
I received this error too, from deploying a site first without SSL installed, then trying to add in a new SSL config.

I believe the correct resolution may be to blow away this directory before mupx setup:
`/opt/app-name/config`

**Comment by MasterJames** [comment]
Sounds like the file might be locked when being used. Maybe there's a mupx stop or something to try? 
https://github.com/arunoda/meteor-up/tree/mupx#other-utility-commands

**Comment by AndreasGalster** [comment]
Where is that opt folder? I'm guessing that's when I ssh in my virtual machine, right? In the project folder I only have a letsencrypt folder, if I go to home I only have my app's name folder which contains only letsencrypt.

**Comment by MasterJames** [comment]
Opt folder would be on root I believe but that sounds like a confusion between mup and mupx where stud was replaced with docker images and nginx.

**Comment by AndreasGalster** [comment]
I might have set an app up with mup vs mupx before. Renaming my appName (and stopping the already running app) helped me get it done!

**Comment by hloydl** [comment]
I can confirm the solution from @markoshust 

Story goes like this: 
setup mup   (somehow missed mupx at that time)
setup mupx
created certificates using letsencrypt
added ssl in mup.json:

```
...
"ssl": {
    "certificate": "./fullchain.pem", // this is a bundle of certificates as created by letsencrypt
    "key": "./privkey.pem", // this is the private key of the certificate as created by letsencrypt
    "port": 443 // 443 is the default value and it's the standard HTTPS port
  },
...
```

mupx setup
   ...error "Copying SSL certificate bundle: FAILED"

Solution: 
cd /opt/myApp
rm -rf ./config

**Comment by brajt** [comment]
I get the same error:
```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Invalid configuration file mup.json: SSL certificate file does not exists.
```
but unfortunately removing even the whole project from the production server doesn't solve the issue.

I get my SSL from Let's Encrypt, use the following code:
```
  "ssl": {
    "pem": "./ssl.pem"
  }
```
and both mupx.json and ssl.pem files are in root folder.

**Comment by indesignlatam** [comment]
I just got this same issue using mupx, it was solved as stated above, removing the opt folder.

**Comment by LennonR** [comment]
I just had this same issue and resolved simply by changing my appName to a single word.

**Comment by srbdp** [comment]
I think changing appName resolves it because it creates a new directory. Same ad rm -rm ./config in /opt/myApp above.

@hloydl's solution worked for me.

**Comment by CarlQLange** [comment]
This shouldn't be closed - this still happens. Happened to me earlier today.

**Comment by vedovato** [comment]
Tried @hloydl suggestion without success. When renamed my app, all gone right

**Comment by eric-burel** [comment]
I had a similar issue recently while moving an old app to the new `proxy` options, with custom SSL certificate. I had to wipe the `/opt/` folder but also to kill all running docker instances because port 80 was busy during `mup deploy`.
