### ISSUE TITLE
mup not compatible with meteor 1.2.0.1

### ISSUE THREAD

**Issue by daguangli** [arunoda/meteor-up-legacy#671]
mup fails after meteor upgrade to 1.2.0.1

```
 -----------------------------------STDERR-----------------------------------
 npm WARN package.json meteor-dev-bundle@0.0.0 No description
 npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
 npm WARN package.json meteor-dev-bundle@0.0.0 No README data
 ../src/coroutine.cc: In function ‘void* find_thread_id_key(void*)’:
 ../src/coroutine.cc:64:53: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
   for (pthread_key_t ii = coro_thread_key - 1; ii >= 0; --ii) {
                                                      ^
 ../src/coroutine.cc:90:3: warning: ‘thread_id’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (tls == thread_id) {
    ^
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed

 0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
 Latest deployment failed! Reverted back to the previous version.
 -----------------------------------STDOUT-----------------------------------
 regex@0.2.1 node_modules/ansi-regex

 ansi-styles@1.1.0 node_modules/ansi-styles

 escape-string-regexp@1.0.3 node_modules/escape-string-regexp
```

**Comment by chompomonim** [comment]
Same here :/

**Comment by cosio55** [comment]
I got another error also, but I think it has something to do with crosswalk:

```
Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

Meteor app path    : /Users/jeronimocosio/vno/vnomvp
Using buildOptions : {}
% Error during processing of action! Attempting to revert...
% Error during processing of action! Attempting to revert...
% Failed to install 'cordova-plugin-crosswalk-webview':Error: Uh oh!
"/Users/jeronimocosio/vno/vnomvp/.meteor/local/cordova-build/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java" already exists!
  at Object.module.exports.common.copyNewFile (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
  at Object.module.exports.source-file.install (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
  at installWrapper (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
  at Object.ActionStack.process (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
  at handleInstall (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:576:20)
  at /Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:363:28
  at _fulfilled (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
  at /Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
  at flush (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:448:13)

=> Errors executing Cordova commands:

   While adding plugin cordova-plugin-crosswalk-webview@1.2.0 to Cordova
   project:
   Error: Uh oh!

   "/Users/jeronimocosio/vno/vnomvp/.meteor/local/cordova-build/platforms/android/src/org/crosswalk/engine/XWalkWebViewEngine.java"
   already exists!
   at Object.module.exports.common.copyNewFile
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/common.js:67:19)
   at Object.module.exports.source-file.install
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
   at installWrapper
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/platforms/platforms.js:77:32)
   at Object.ActionStack.process
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/util/action-stack.js:68:25)
   at handleInstall
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:576:20)
   at
   /Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:363:28
   at _fulfilled
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:509:49
   at flush
   (/Users/jeronimocosio/.meteor/packages/meteor-tool/.1.1.8.k3mszd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at process._tickCallback (node.js:448:13)
   

=> Build Error. Check the logs printed above.
```

**Comment by thuanphandev** [comment]
you should change file `mup.json` like this:

```
{ ...
"setupNode": true,
"nodeVersion": "0.10.40",
...}
```

then `mup setup`  then `mup deploy` after that!

**Comment by daguangli** [comment]
Hi thuanmaster, just tried your solution. mup setup was ok, but mup deploy still threw the same error.

**Comment by thuanphandev** [comment]
let's try update mup packages (ver 0.11.2) then `mup setup` and `mup deploy` again!
If not successful, show me options (not 'servers' and 'env') in  `mup.json`

**Comment by daguangli** [comment]
what I have done:
npm update -g mup (empty output)
mup setup (success)
mup deploy (same error)

my mup.json:
  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": true,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": true,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.40",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Show a progress bar during the upload of the bundle to the server. 
  // Might cause an error in some rare cases if set to true, for instance in Shippable CI
  "enableUploadProgressBar": true,

  // Application name (No spaces)
  "appName": "EverGreen",

  // Location of app (local directory)
  "app": "..",

the setup used to work with meteor 1.1.0.3.

Thanks!

**Comment by sean-stanley** [comment]
+1 I just tried @thuanmaster's suggestion and got the same result as @daguangli.

Hang on though, running node --version on my server still shows 0.10.31. I'll try manually upgrading to 0.10.40 and try again.

**Comment by thuanphandev** [comment]
you should update `mup package` by command `npm install -g mup`, i think your mup version is  `0.11.1`.
while run mup deploy, open another cmd run `mup logs -f` and show me what error while `mup deploy`

**Comment by daguangli** [comment]
I ran npm install -g mup, and it tells me the version is 0.11.2. Below is the out put of mup logs -f :

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]     ^[52.26.221.37]
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #1[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #2[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #3

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #4[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #5[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #6[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]   ^[52.26.221.37]
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #7[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #8[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]
error: Script restart attempt #9[52.26.221.37]

/opt/EverGreen/app/programs/server/node_modules/fibers/future.js:245[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37] throw(ex);[52.26.221.37]
 [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37]  [52.26.221.37
Error: /opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
    at Module.require (module.js:364:17)[52.26.221.37]
    at require (module.js:380:17)[52.26.221.37]
    at bindings (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)[52.26.221.37]
    at Object.<anonymous> (/opt/EverGreen/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)[52.26.221.37]
    at Module._compile (module.js:456:26)[52.26.221.37]
    at Object.Module._extensions..js (module.js:474:10)[52.26.221.37]
    at Module.load (module.js:356:32)[52.26.221.37]
    at Function.Module._load (module.js:312:12)[52.26.221.37]
error: Forever detected script exited with code: 8[52.26.221.37]

> > stepping down to gid: meteoruser[52.26.221.37]
> > stepping down to uid: meteoruser[52.26.221.37]

**Comment by sean-stanley** [comment]
after i double checked my server had node 0.10.40 installed and I installed the latest version of mup and redeployed everything worked fine for me.

To get mup to the latest version I also installed the latest version of npm first with `npm install npm -g`  and ran `npm install mup -g` which also made sure all of mup's dependencies were at the latest versions. 

I hope the others with this problem get their systems working quickly but I can definately say the latest version of mup can deploy a meteor 0.1.2.0.1 app.

Thanks for the great package.

**Comment by thuanphandev** [comment]
Look like some problem in npm packages. Try update npm `npm install npm -g` and modify this option to `mup.json` 

```
"deployCheckWaitTime": 15
```

then setup and deploy again

**Comment by steinitz-zz** [comment]
@thuanmaster @sean-stanley I confirm that your instructions work.  Thank you for sharing your knowledge.  For those still having problems, remember that, as @thuanmaster pointed out, you have to run mup setup after changing the node version to 0.10.40 (in mup.json) -- running mup deploy doesn't update node.

**Comment by chompomonim** [comment]
Confirm, that for me this path also works:

> update mup.json (set node to 0.10.40)
> npm install npm -g
> npm install mup -g
> mup setup
> mup deploy

**Comment by mgruen** [comment]
The path below also works for me:

update mup.json (set node to 0.10.40)
npm update mup -g
mup setup
mup deploy

**Comment by maciej-trebacz** [comment]
I have exact same issue, but for Meteor 1.1.x project. I've updated mup to latest version, I've updated node version in mup.json to 0.10.40, but still get this error:

```
[olapp.karni.net.au] x Invoking deployment process: FAILED
```

`mup logs -f` output:

```
[olapp.karni.net.au] Error: Can't find npm module 'body-parser'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?[olapp.karni.net.au]
[olapp.karni.net.au]     at Object.Npm.require (/opt/olord/app/programs/server/boot.js:147:17)[olapp.karni.net.au]
[olapp.karni.net.au]     at assert (packages/iron:router/lib/body_parser_server.js:1:1)[olapp.karni.net.au]
[olapp.karni.net.au]     at /opt/olord/app/programs/server/packages/iron_router.js:1269:4[olapp.karni.net.au]
[olapp.karni.net.au]     at /opt/olord/app/programs/server/packages/iron_router.js:1455:3[olapp.karni.net.au]
[olapp.karni.net.au]     at /opt/olord/app/programs/server/boot.js:205:10[olapp.karni.net.au]
[olapp.karni.net.au]     at Array.forEach (native)[olapp.karni.net.au]
[olapp.karni.net.au]     at Function._.each._.forEach (/opt/olord/app/programs/server/node_modules/underscore/underscore.js:79:11)[olapp.karni.net.au]
[olapp.karni.net.au]     at /opt/olord/app/programs/server/boot.js:116:5[olapp.karni.net.au]
[olapp.karni.net.au] error: Forever detected script exited with code: 8[olapp.karni.net.au]
```

Any help would be appreciated.

Update: I've deployed the app using the [traditional way](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-meteor-js-application-on-ubuntu-14-04-with-nginx) and it worked fine. I'd still like to use mup though, because manual uploading is a pain.

**Comment by daguangli** [comment]
I got it working with meteor 1.2.0.1 + node 0.10.40, had no luck with meteor 1.1.x.x. Hope this can help.

**Comment by babnik63** [comment]
I have the same problem:

x Invoking deployment process: FAILED

```
-----------------------------------STDERR-----------------------------------
ode_root_dir=/root/.node-gyp/0.10.40',
gyp info spawn args   '-Dmodule_root_dir=/opt/helpdesk/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info ok 
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
```

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 80: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    nsi-regex@0.2.1 node_modules/ansi-regex

```
ansi-styles@1.1.0 node_modules/ansi-styles

chalk@0.5.1 node_modules/chalk

escape-string-regexp@1.0.3 node_modules/escape-string-regexp

strip-ansi@0.3.0 node_modules/strip-ansi

supports-color@0.2.0 node_modules/supports-color

has-ansi@0.1.0 node_modules/has-ansi

eachline@2.3.3 node_modules/eachline

type-of@2.0.1 node_modules/type-of

amdefine@1.0.0 node_modules/amdefine

asap@2.0.3 node_modules/asap

meteor-promise@0.4.8 node_modules/meteor-promise

underscore@1.5.2 node_modules/underscore

promise@7.0.4 node_modules/promise

source-map-support@0.3.2 node_modules/source-map-support

semver@4.1.0 node_modules/semver

source-map@0.1.32 node_modules/source-map

fibers@1.0.5 node_modules/fibers
Waiting for MongoDB to initialize. (5 minutes)
connected
helpdesk stop/waiting
helpdesk start/running, process 4824
Waiting for 15 seconds while app is booting up
Checking is app booted or not?
helpdesk stop/waiting
helpdesk start/running, process 4894
----------------------------
```

**Comment by MasterJames** [comment]
Did you try extending the wait time? 
    "deployCheckWaitTime": 120

**Comment by yumikohey** [comment]
@MasterJames I tried to change "deployCheckWaitTime" to 120. It doesn't work. I encountered the same error as @babnik63 .

**Comment by cstrat** [comment]
I am getting these same errors.

Completely rebuilt my local environment and tried deploying. I get almost word for word the same errors @babnik63 has posted above.

**Comment by yumikohey** [comment]
@cstrat I deployed successfully after I get rid of the "MONGO_URL" in config environment in mup.json

**Comment by cstrat** [comment]
I don't have mongo URL in mine.
I will try setting my 'setupMongo' flag to false, as it already is
installed, I am just pushing an update to the app.

**Comment by yumikohey** [comment]
@cstrat Do you have a repo anywhere so I can take a look?

**Comment by sonicviz** [comment]
I was getting the same errors for Meteor 1.2 mup but then I tried to login and check via putty and realized my dynamic IP address had changed and it was the AWS Security SSH rule that was blocking it. I reset it to current IP and mup worked just fine.

**Comment by babnik63** [comment]
Owere environment is so simple and nothing is changed. But still the same error. :-(

**Comment by jerocosio** [comment]
I am also having a similar error, I already tried updating npm and then mup, changing the node version to 0.10.40, and setting the deploycheckwaittime to 160 and this is the error I am getting:

```
[104.236.158.125] - Uploading bundle
[104.236.158.125] - Uploading bundle: SUCCESS
[104.236.158.125] - Setting up Environment Variables
[104.236.158.125] - Setting up Environment Variables: SUCCESS
[104.236.158.125] - Invoking deployment process
[104.236.158.125] x Invoking deployment process: FAILED

    -----------------------------------STDERR-----------------------------------
    pawn args   '-Dnode_lib_file=node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/opt/vynoapp/tmp/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    gyp info ok 
    npm WARN package.json meteor-dev-bundle@0.0.0 No description
    npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
    npm WARN package.json meteor-dev-bundle@0.0.0 No README data
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 81: Connection refused
    Latest deployment failed! Reverted back to the previous version.
    -----------------------------------STDOUT-----------------------------------
    ansi-regex@0.2.1 node_modules/ansi-regex

    ansi-styles@1.1.0 node_modules/ansi-styles

    chalk@0.5.1 node_modules/chalk

    escape-string-regexp@1.0.3 node_modules/escape-string-regexp

    supports-color@0.2.0 node_modules/supports-color

    has-ansi@0.1.0 node_modules/has-ansi

    strip-ansi@0.3.0 node_modules/strip-ansi

    eachline@2.3.3 node_modules/eachline

    type-of@2.0.1 node_modules/type-of

    amdefine@1.0.0 node_modules/amdefine

    asap@2.0.3 node_modules/asap

    meteor-promise@0.4.8 node_modules/meteor-promise

    underscore@1.5.2 node_modules/underscore

    promise@7.0.4 node_modules/promise

    source-map-support@0.3.2 node_modules/source-map-support

    semver@4.1.0 node_modules/semver

    source-map@0.1.32 node_modules/source-map

    fibers@1.0.5 node_modules/fibers
    Waiting for MongoDB to initialize. (5 minutes)
    connected
    vynoapp stop/waiting
    vynoapp start/running, process 30175
    Waiting for 160 seconds while app is booting up
    Checking is app booted or not?
    vynoapp stop/waiting
    vynoapp start/running, process 30627
    ----------------------------------------------------------------------------

```

**Comment by yumikohey** [comment]
@cosio55 I'm interested in taking a look and see if anything I can help. Could you give me more info?

**Comment by cmddavid** [comment]
This worked for me:

update mup.json (set node to 0.10.40)
npm update mup -g
mup setup
mop deploy

I had to try mup deploy 2 or 3 times before it actually succeeded.

**Comment by JuanCrg90** [comment]
I used the solution of @cmddavid   and works for me

**Comment by jerocosio** [comment]
Sure @yumikohey I already could make it work, currently I am deploying to a DO virtual machine and my DB is on Compose, my mup.json file is:

```
{
  "servers": [
    {
      "host": "ACTUAL IP ADDRESS",
      "username": "ACTUAL USER",
      "password": "ACTUAL PASSWORD"
    }
  ],

  // Install MongoDB in the server, does not destroy local MongoDB on future setup
  "setupMongo": false,

  // WARNING: Node.js is required! Only skip if you already have Node.js installed on server.
  "setupNode": false,

  // WARNING: If nodeVersion omitted will setup 0.10.36 by default. Do not use v, only version number.
  "nodeVersion": "0.10.40",

  // Install PhantomJS in the server
  "setupPhantom": true,

  // Application name (No spaces)
  "appName": "vynoapp",

  // Location of app (local directory)
  "app": "~/vno/vnomvp",

  // Configure environment
  "env": {
    "PORT": 81,
    "ROOT_URL": "http://vyno.mx",
    "MONGO_URL": "ACTUAL URL",
    "MONGO_OPLOG_URL": "ACTUAL URL"
  },

  // Meteor Up checks if the app comes online just after the deployment
  // before mup checks that, it will wait for no. of seconds configured below
  "deployCheckWaitTime": 160

}
```

I changed the flag of setup node which I had set to false and I could then deploy correctly, so proabably that was the error I was making.

**Comment by MomchilGorchev** [comment]
I had the same error output as @cosio55 .
This steps made it work for me:

`update mup.json (set node to 0.10.40)`
`npm install npm -g`
`npm install mup -g`
`mup setup`
`mup deploy`

**Comment by RavikumarNagaraja** [comment]
Thank u guys fixed this, but one step i need to add, for Ubuntu production box, my node version was 0.10.36, i had to update to 0.10.40 for that i ran the following command in production box i.e.

Production Ubuntu Machine/Box:
curl -sL https://deb.nodesource.com/setup_0.10 | sudo -E bash -
sudo apt-get install -y nodejs

MUP Machine/Box:
update mup.json (set node to 0.10.40)
npm install npm -g
npm install mup -g
mup setup
mup deploy

**Comment by thinklinux** [comment]
Confirmed from me too! This works.

update mup.json (set node to 0.10.40)
npm install mup -g
mup setup
mup deploy

**Comment by rootedsoftware** [comment]
I had the same error output as @cosio55 as well. I setup a new server on Digital Ocean and started from scratch. The only commands I ran on this new server were `sudo apt-get update` and `sudo npm install -g mup`. I then did the mup commands locally to get the local meteor app deployed. I can confirm the node version is 0.10.40, but I still get the same connection error as before.

**Comment by MasterJames** [comment]
Some may find mupx resolves their problems.
I noticed in cosio logs something about port 81.
I think posting your settings files as well as log files and any environment information versions etc. would be helpful too.

**Comment by rootedsoftware** [comment]
@MasterJames Yes, mupx does resolve the problem of running a Meteor 1.2+ app for me, but it also creates another problem. I can't specify custom NGINX settings in MUPX. Or at least not settings that are sticky between mupx deploys. This is the main reason I didn't want to switch to mupx yet. The docker containers let me access the nginx.conf file, but the changes I make don't stay in place after I do a mup deploy.

**Comment by MasterJames** [comment]
Right it installs docker here...
https://github.com/arunoda/meteor-up/blob/mupx/scripts/linux/install-docker.sh
For SSL it says its using nginx
https://github.com/meteorhacks/mup-frontend-server

Anyway it calls
https://github.com/meteorhacks/mup-frontend-server/blob/master/lib/install-nginx.sh
which copies the nginx.conf
https://github.com/meteorhacks/mup-frontend-server/blob/master/lib/nginx.conf
[That you would like to customize?]
from in here...
https://github.com/meteorhacks/mup-frontend-server/blob/master/lib/copy-files.sh

This doesn't seem particularly easy to achieve looking into it I agree.
Maybe you technically have to fork the repo to change the conf and reference that version here to.
https://github.com/arunoda/meteor-up/blob/mupx/scripts/linux/verify-ssl-configurations.sh#L19
other then a modification to the code that copies it.

**Comment by MasterJames** [comment]
You can also do a "docker push" after making changes to a docker image I believe.
http://blog.thoward37.me/articles/where-are-docker-images-stored/
and reference that one or it updates it or something like that?

**Comment by samwightt** [comment]
Yes! This works for me too:

update mup.json (set node to 0.10.40)
npm update mup -g
mup setup
mup deploy

**Comment by cstrat** [comment]
@yumikohey I fixed my issue!

The problem that I had was I had node installed on my server and the version of node was 0.10.36.
MUP was configured to package 0.10.40 - however it appears that if you have node directly installed on the server, MUP doesn't do anything with node.
My mup.json was all correct (0.10.40) I kept getting the deployment error until I logged into my server and ran:

sudo n 0.10.40

---

It appears that @sean-stanley had the same fix that I did 17 days ago, I just didn't realise that this was the behaviour of MUP.

**Comment by roelvan** [comment]
Works for me too:

```
update mup.json (set node to 0.10.40)
npm update mup -g
mup setup
mup deploy
```

**Comment by c9s** [comment]
I forked this repo and started a new project from this basis,  the deploy script will fix the bcrypt issue automatically

You can just install the mup from here https://github.com/c9s/meteor-up

**Comment by c9s** [comment]
Remember to setup node 0.10.44, meteor 1.3 requires node 0.10.41+ versions.
